# Generated by Django 5.1 on 2026-05-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_videoexercicio_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
