# Generated by Django 5.1 on 2026-05-08 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_variacaoexercicio_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='nome',
            field=models.CharField(max_length=300),
        ),
    ]
