# Generated by Django 5.1 on 2026-05-25 23:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_videoexercicio_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='gif',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='gif'),
        ),
    ]
