# Generated by Django 5.1 on 2026-05-13 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_videoexercicio_gif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variacaoexercicio',
            name='gif',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='gifs/'),
        ),
    ]
