# Generated by Django 5.1 on 2026-06-22 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_variacaoexercicio_gif"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="personal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="alunos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrador"),
                    ("PERSONAL", "Personal"),
                    ("ALUNO", "Aluno"),
                ],
                default="PERSONAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="cref",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="telefone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
