# Generated by Django 5.1 on 2026-05-28 22:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_variacaoexercicio_gif'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exercicio',
        ),
        migrations.RemoveField(
            model_name='exerciciotreino',
            name='exercicio',
        ),
        migrations.AlterUniqueTogether(
            name='variacaoexercicio',
            unique_together={('exercicio', 'nome')},
        ),
        migrations.RemoveField(
            model_name='videoexercicio',
            name='gif',
        ),
        migrations.AddField(
            model_name='variacaoexercicio',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videoexercicio',
            name='categoria',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='exerciciotreino',
            name='variacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treinos', to='core.variacaoexercicio'),
        ),
        migrations.AlterField(
            model_name='grupomuscular',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='treino',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='videoexercicio',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.RemoveField(
            model_name='variacaoexercicio',
            name='grupo_muscular',
        ),
    ]
