# Generated by Django 6.0.7 on 2026-08-17 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_aluno_personal_usuario_tipo_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='asaas_customer_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
