# Generated by Django 6.0.7 on 2026-08-19 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_usuario_asaas_customer_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(db_index=True, max_length=200, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('PROCESSED', 'Processado'), ('IGNORED', 'Ignorado'), ('FAILED', 'Falhou')], max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_subscription_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('OVERDUE', 'Inadimplente'), ('CANCELLED', 'Cancelada'), ('PENDING', 'Pendente')], default='PENDING', max_length=20)),
                ('plano', models.CharField(default='mensal', max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assinatura', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
