# Generated by Django 6.0.7 on 2026-08-20 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_webhookevent_assinatura'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoAsaas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asaas_payment_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('CONFIRMED', 'Confirmado'), ('RECEIVED', 'Recebido'), ('OVERDUE', 'Inadimplente'), ('REFUNDED', 'Estornado'), ('DELETED', 'Removido')], default='PENDING', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('recebido_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('assinatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='core.assinatura')),
            ],
        ),
    ]
