# Generated by Django 6.0.7 on 2026-08-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_pagamentoasaas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assinatura',
            name='plano',
            field=models.CharField(choices=[('MENSAL', 'Plano Mensal'), ('ANUAL', 'Plano Anual')], default='MENSAL', max_length=20),
        ),
    ]
